NAME = rush-02

FLAGS = -Wall -Werror -Wextra

SRCS = ft_atoi.c ft_count.c ft_findsft.c ft_nbr2str.c ft_print.c main.c

all: $(NAME)

$(NAME):
		gcc $(FLAGS) -o $(NAME) $(SRCS)

fclean:
		rm -f $(NAME)

re:
		fclean all


